channels:
- conda-forge
dependencies:
- python=3.9.13
- pip<=25.3
- pip:
  - mlflow==2.9.2
  - cloudpickle==3.1.2
  - numpy==1.26.2
  - packaging==23.2
  - psutil==7.2.1
  - pyyaml==6.0.1
  - scikit-learn==1.3.2
  - scipy==1.13.1
name: mlflow-env
