FROM python:3.9-slim

WORKDIR /mlflow

# Install MLflow
RUN pip install --no-cache-dir mlflow==2.9.2 boto3

# Create directories
RUN mkdir -p /mlflow/mlruns /mlflow/models

# Expose MLflow UI port
EXPOSE 5000

# Run MLflow server
CMD ["mlflow", "server", \
     "--host", "0.0.0.0", \
     "--port", "5000", \
     "--backend-store-uri", "sqlite:///mlflow/mlruns/mlflow.db", \
     "--default-artifact-root", "/mlflow/models"]
